=== TangoTwo/khp-hgb/ss19/ssd/ex05/SSD4_Uebung5_XMLParser_ZumAusarbeiten/addressbook.dtd
<!ELEMENT addressbook ((person | company)*)>
<!ATTLIST addressbook owner IDREF #REQUIRED
	  date CDATA #IMPLIED>
<!ELEMENT person (firstname, lastname, email)>
<!ATTLIST person id ID #REQUIRED>
<!ELEMENT firstname (#PCDATA)> 
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ATTLIST email type (home | business) "business">
<!ELEMENT company (companyname, url)>
<!ATTLIST company id ID #REQUIRED>
<!ELEMENT companyname (#PCDATA)>
<!ELEMENT url (#PCDATA)>

=== TangoTwo/khp-hgb/ss19/ssd/ex05/SSD4_Uebung5_XMLParser_ZumAusarbeiten/adressbook_out.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE addressbook SYSTEM "addressbook.dtd">
<!-- Date and Time:Thu Apr 04 14:56:55 CEST 2019 -->
<addressbook owner="p1" date="2019-04-05">
    <person id="p1">
        <firstname>Max</firstname>
        <lastname>Mustermann</lastname>
        <email type="business">max.mustermann@fh-hagenberg.at</email>
    </person>
    <company id="c1">
        <companyname>FH</companyname>
        <url>www.fh-ooe.at</url>
    </company>
    <person id="p2">
        <firstname>Mina</firstname>
        <lastname>Musterfrau</lastname>
        <email type="business">mina.musterfrau@fh-hagenberg.at</email>
    </person>
    <person id="p3">
        <firstname>Moritz</firstname>
        <lastname>Musterkind</lastname>
        <email type="home">moritz.musterkind@gmail.com</email>
    </person>
</addressbook>
